Importing required Python packages

In [1]:
import numpy as np
import pandas as pd
from sklearn import datasets


Creating a numpy array

In [5]:
arr1=np.array([1, 2, 3, 4, 5])

Array indexing and slicing
Slicing: Elements returned are element at index specified in start position and excludes the element provided at the end index

In [9]:
print("Element at index 1 ==",arr1[1])
print("Elements from index 1 to 3==",arr1[1:3])

Element at index 1 == 2
Elements from index 1 to 3== [2 3]


Getting the datatype of the array

In [10]:
print(arr1.dtype)

int64


Numpy shape is essential for knowing the dimensions of the data that we are performing tasks on

In [15]:
arr2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8],[7,8,9,0]])
arr2.shape

(3, 4)

Now reshaping the array might be required sometimes, for example when you are dealing with a dataset where you want to convert a 1D array to a 2D array. Here np.reshape(2,4) means that the dataset is reshaped into a 2 arrays with four elements each.

In [18]:
arr3= np.array([1, 2, 3, 4, 5, 6, 7, 8])
arr4=arr3.reshape(2,4)
print(arr4)



[[1 2 3 4]
 [5 6 7 8]]


**Intro to Pandas** 


In [36]:
data1 = {
  "calories": [420, 380, 390],
  "duration": [50, 40, 45],
}

Loading the data into a pandas dataframe

In [38]:
df=pd.DataFrame(data1)
df.head()

calories  duration
0       420        50
1       380        40
2       390        45

To get valuable statistics regarding the dataset use describe()

In [39]:
df.describe()


calories  duration
count    3.000000       3.0
mean   396.666667      45.0
std     20.816660       5.0
min    380.000000      40.0
25%    385.000000      42.5
50%    390.000000      45.0
75%    405.000000      47.5
max    420.000000      50.0

You can also load csv or json files to a pandas dataframe and then perform certain data cleaning operations

**Intro to sklearn**

Sklearn or Scikit-learn is a python library which focuses on modelling the data. It provides many ml models such as supervised learning models Linear Regression ,SVM, Unsupervised such as PCA, Clustering, Cross validation and many more. Sklearn also provides dataset such as the iris and digits dataset. Here we load the iris dataset, get their features and target_names and print first 10 rows of data

In [41]:
from sklearn.datasets import load_iris
iris = load_iris()
X = iris.data
y = iris.target
feature_names = iris.feature_names
target_names = iris.target_names
print("Feature names:", feature_names)
print("Target names:", target_names)
print("\nFirst 10 rows of X:\n", X[:10])

Feature names: ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
Target names: ['setosa' 'versicolor' 'virginica']

First 10 rows of X:
 [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]]
